version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: glpi_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: glpidb
      MYSQL_USER: glpiuser
      MYSQL_PASSWORD: glpipassword
    volumes:
      - db_data:/var/lib/mysql

  glpi:
    image: diouxx/glpi
    container_name: glpi_app
    restart: always
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: glpiuser
      DB_PASSWORD: glpipassword
      DB_NAME: glpidb
    depends_on:
      - db

volumes:
  db_data:
